# Site settings
title: pampiridam
smalltalk: "A music school for everyone!"
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  
facebook_username: pampiridam
portfolio_url: 

# Build settings
markdown: kramdown
